# Generated by Django 5.2.12 on 2026-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_depense_validateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommationligne',
            name='groupe_ref',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Référence groupe'),
        ),
    ]
