# Generated by Django 5.2.12 on 2026-05-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_add_depense_refactor_pieces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommationligne',
            options={'ordering': ['-date'], 'verbose_name': 'Ligne de dépense', 'verbose_name_plural': 'Lignes de dépense'},
        ),
        migrations.AddField(
            model_name='budgetannuel',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de clôture de l'exercice"),
        ),
        migrations.AddField(
            model_name='budgetannuel',
            name='est_cloture',
            field=models.BooleanField(default=False, verbose_name='Exercice clôturé'),
        ),
        migrations.AlterField(
            model_name='consommationligne',
            name='groupe_ref',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Référence groupe (legacy)'),
        ),
        migrations.AlterField(
            model_name='consommationligne',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Note / libellé'),
        ),
    ]
