# Generated by Django 5.2.12 on 2026-05-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_consommationligne_postes'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='libelle_hors_budget',
            field=models.CharField(blank=True, max_length=300, verbose_name='Libellé (hors budget)'),
        ),
        migrations.AlterField(
            model_name='consommationligne',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='budget.lignebudgetaire', verbose_name='Ligne budgétaire'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='budget.budget', verbose_name='Budget'),
        ),
    ]
