# Generated by Django 5.2.12 on 2026-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_hors_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignebudgetaire',
            name='section',
            field=models.CharField(choices=[('REVENU', 'Revenu'), ('DEPENSE', 'Dépense'), ('BUDGET', 'Budget')], default='BUDGET', max_length=10, verbose_name='Section'),
        ),
    ]
